"""Test migration

Revision ID: bcf97dc5811a
Revises: 
Create Date: 2023-02-01 22:31:03.987562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf97dc5811a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selectedheroes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('selectedteams',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Hero', sa.Integer(), nullable=True),
    sa.Column('Team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Hero'], ['selectedheroes.Id'], ),
    sa.ForeignKeyConstraint(['Team'], ['teams.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selectedteams')
    op.drop_table('teams')
    op.drop_table('selectedheroes')
    # ### end Alembic commands ###
